defaultContentLanguage = "en"
title = "Hedera Developers and Projects"
baseURL = "https://hedera-developers.netlify.app/"
description = ""

log = true
logFile = "hugo-build.log"

[markup.goldmark.renderer]
unsafe= true
